version: 2

defaults: &defaults
  working_directory: ~/materialize-hooked
  docker:
    - image: circleci/node:latest-browsers
  environment:
    TZ: '/usr/share/zoneinfo/America/Los_Angeles'

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package.json checksum
            # when this file is changed, this key will fail
            - materialize-hooked-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
            - materialize-hooked-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - materialize-hooked-{{ .Branch }}
            # Find the most recent cache used from any branch
            - materialize-hooked-master
            - materialize-hooked-
      - run: date
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: materialize-hooked-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/materialize-hooked
      - run:
          name: Lint
          command: yarn lint

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/materialize-hooked
      - run:
          name: Lint
          command: yarn build

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/materialize-hooked
      - run:
          name: Test
          command: yarn test:ci
      - run:
          name: Send CodeCov Results
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_KEY

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/materialize-hooked
      - run:
          name: 'Make sure we can commit to github'
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Release
          command: yarn run deploy-storybook

workflows:
  version: 2
  build_and_test:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/

      - lint:
          requires:
            - install
          filters:
            tags:
              only: /.*/

      - test:
          requires:
            - install
          filters:
            tags:
              only: /.*/

      - build:
          requires:
            - install
          filters:
            tags:
              only: /.*/

      - release:
          requires:
            - build
            - test
            - lint
          filters:
            branches:
              only:
                - master
